### ISSUE TITLE
As a USER I can view events I’m attending on the home page in descending order

### ISSUE THREAD

**Issue by TheGarrett** [TheGarrett/EventsWebsite#2]
AC01 – As a USER I can view my events on the Home page
GIVEN I am an Accenture employee
AND I have logged into the website
AND I have events
WHEN I navigate to the Home page
THEN I can see a list of all the events I am attending
AND I can see the events title
AND I can see the events date
AND I can see the events sender
AND I can see the events description
AND the events are in descending ordered based on the date of the event

AC02 – As a USER if I’m attending no events then I can see text telling me I’m not
GIVEN I am an Accenture employee
AND I have logged into the website
AND I have no events
WHEN I navigate to the Home page
THEN I can see text telling me I do not have any events

**Comment by adkel92** [comment]
Looks good to me, All AC's met
